-- Create RSVP table (email upsertable)
create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  attendance text not null check (attendance in ('attending','declining')),
  guests integer not null default 0,
  message text not null default '',
  created_at timestamptz not null default now()
);

-- Unique by email to allow upsert/overwrite
create unique index if not exists rsvps_email_key on public.rsvps (email);

-- Storage bucket for guest photos
-- In Supabase Dashboard > Storage > Create bucket "guest-photos" (public: ON)
-- Optional: if you keep it private, server code must sign URLs for display.

-- If you prefer to keep RLS enabled on rsvps, add permissive policies for service_role
-- (the server uses SUPABASE_SERVICE_ROLE so it bypasses RLS; below is for completeness)
alter table public.rsvps enable row level security;
do $$ begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='rsvps' and policyname='allow_all_service'
  ) then
    create policy "allow_all_service" on public.rsvps
      for all using (true) with check (true);
  end if;
end $$;

